import io

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)

from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.platypus import Image, PageBreak
from app.reports.charts import ChartGenerator
from app.reports.style import *


class PDFGenerator:

    @staticmethod
    def _metric_card(title, value, color):

        table = Table(
            [
                [Paragraph(title, CARD_TITLE)],
                [Paragraph(str(value), CARD_VALUE)]
            ],
            colWidths=2.2 * inch
        )

        table.setStyle(TableStyle([

            ("BACKGROUND", (0, 0), (-1, -1), color),

            ("BOX", (0, 0), (-1, -1), 1, colors.white),

            ("BOTTOMPADDING", (0, 0), (-1, -1), 12),

            ("TOPPADDING", (0, 0), (-1, -1), 12),

            ("ALIGN", (0, 0), (-1, -1), "CENTER"),

            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),

        ]))

        return table

    @staticmethod
    def _footer(canvas, doc):

        canvas.saveState()

        canvas.setFont("Helvetica", 9)

        canvas.setFillColor(colors.grey)

        canvas.drawString(
            40,
            20,
            "Generated by AgentBench"
        )

        canvas.drawRightString(
            560,
            20,
            f"Page {doc.page}"
        )

        canvas.restoreState()

    @staticmethod
    def generate(report):

        buffer = io.BytesIO()

        doc = SimpleDocTemplate(
            buffer,
            rightMargin=40,
            leftMargin=40,
            topMargin=40,
            bottomMargin=40,
        )

        story = []

        # -------------------
        # COVER PAGE
        # -------------------

        story.append(
            Paragraph(
                "AGENTBENCH",
                TITLE
            )
        )

        story.append(
            Paragraph(
                "AI Benchmark Evaluation Report",
                SUBTITLE
            )
        )

        story.append(
            Spacer(1, 25)
        )

        story.append(
            Paragraph(
                "<b>Benchmark Prompt</b>",
                HEADING
            )
        )

        story.append(
            Paragraph(
                report["prompt"],
                BODY
            )
        )

        story.append(
            Spacer(1, 20)
        )

        # ------------------
        # SUMMARY CARDS
        # ------------------

        cards = Table([
            [

                PDFGenerator._metric_card(
                    "Winner",
                    report["winner"],
                    colors.HexColor("#10B981")
                ),

                PDFGenerator._metric_card(
                    "Avg Score",
                    report["average_score"],
                    colors.HexColor("#2563EB")
                ),

                PDFGenerator._metric_card(
                    "Avg Latency",
                    f'{report["average_latency"]} ms',
                    colors.HexColor("#F59E0B")
                )

            ]
        ])

        story.append(cards)

        story.append(
            Spacer(1, 30)
        )

        story.append(
            Paragraph(
                "Benchmark Overview",
                HEADING
            )
        )

        overview = Table([

            ["Benchmark ID", report["benchmark_id"]],

            ["Models Tested", report["total_models"]],

            ["Winner", report["winner"]],

            ["Fastest Model", report["fastest_model"]],

            ["Highest Readability", report["highest_readability"]],

        ])

        overview.setStyle(TableStyle([

            ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#E2E8F0")),

            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),

            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),

            ("TOPPADDING", (0, 0), (-1, -1), 8),

            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),

        ]))

        story.append(overview)

        story.append(
            Spacer(1, 20)
        )

        story.append(
            Paragraph(
                "Ranking",
                HEADING
            )
        )

        ranking_table = [["Rank", "Model", "Score"]]

        for item in report["ranking"]:

            ranking_table.append([
                item["rank"],
                item["model"],
                item["score"]
            ])

        ranking = Table(ranking_table)

        ranking.setStyle(TableStyle([

            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2563EB")),

            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),

            ("BACKGROUND", (0, 1), (-1, -1), colors.white),

            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),

            ("TOPPADDING", (0, 0), (-1, -1), 8),

            ("ALIGN", (0, 0), (-1, -1), "CENTER"),

        ]))

        story.append(ranking)

        # =====================================================
        # PERFORMANCE CHARTS
        # =====================================================

        story.append(PageBreak())

        story.append(
            Paragraph(
                "Performance Charts",
                HEADING
            )
        )

        labels = [
            model["model_name"]
            for model in report["models"]
        ]

        # ------------------------
        # Overall Score Chart
        # ------------------------

        scores = [
            model["overall_score"]
            for model in report["models"]
        ]

        overall_chart = ChartGenerator.create_bar_chart(
            title="Overall Score",
            labels=labels,
            values=scores,
            ylabel="Score"
        )

        story.append(
            Image(
                overall_chart,
                width=450,
                height=250
            )
        )

        story.append(Spacer(1, 20))

        # ------------------------
        # Latency Chart
        # ------------------------

        latencies = [
            model["latency"]
            for model in report["models"]
        ]

        latency_chart = ChartGenerator.create_bar_chart(
            title="Latency",
            labels=labels,
            values=latencies,
            ylabel="Milliseconds"
        )

        story.append(
            Image(
                latency_chart,
                width=450,
                height=250
            )
        )

        # =====================================================
        # MODEL COMPARISON
        # =====================================================

        story.append(PageBreak())

        story.append(
            Paragraph(
                "Model Comparison",
                HEADING
            )
        )

        comparison = [[
            "Rank",
            "Model",
            "Score",
            "Latency",
            "Readability",
            "Keywords",
            "Words"
        ]]

        ranking_map = {
            item["model"]: item["rank"]
            for item in report["ranking"]
        }

        for model in report["models"]:

            comparison.append([

                ranking_map.get(model["model_name"]),

                model["model_name"],

                model["overall_score"],

                model["latency"],

                model["readability_score"],

                model["keyword_score"],

                model["word_count"]

            ])

        comparison_table = Table(comparison)

        comparison_table.setStyle(TableStyle([

            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2563EB")),

            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),

            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),

            ("TOPPADDING", (0, 0), (-1, -1), 8),

            ("ALIGN", (0, 0), (-1, -1), "CENTER"),

        ]))

        story.append(comparison_table)

        # =====================================================
        # RESPONSE ANALYSIS
        # =====================================================

        story.append(PageBreak())

        story.append(
            Paragraph(
                "Response Analysis",
                HEADING
            )
        )

        for model in report["models"]:

            story.append(
                Paragraph(
                    f"<b>{model['model_name']}</b>",
                    SUBTITLE
                )
            )

            story.append(
                Paragraph(
                    "<b>Strengths:</b> "
                    + ", ".join(model["strengths"]),
                    BODY
                )
            )

            story.append(
                Paragraph(
                    "<b>Weaknesses:</b> "
                    + ", ".join(model["weaknesses"]),
                    BODY
                )
            )

            preview = model["response"][:800]

            story.append(
                Paragraph(
                    preview + "...",
                    BODY
                )
            )

            story.append(
                Spacer(1, 20)
            )

        # =====================================================
        # BUILD PDF
        # =====================================================

        doc.build(
            story,
            onFirstPage=PDFGenerator._footer,
            onLaterPages=PDFGenerator._footer
        )

        pdf = buffer.getvalue()

        buffer.close()

        return pdf